-- MySQL Script generated by MySQL Workbench
-- 03/19/17 00:44:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbMyDreamyCom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbMyDreamyCom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbMyDreamyCom` DEFAULT CHARACTER SET utf8 ;
USE `dbMyDreamyCom` ;

-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`groups` (
  `groupID` INT NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(24) NOT NULL,
  `groupType` CHAR(2) NOT NULL,
  PRIMARY KEY (`groupID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `fk_groupID_users` INT NULL,
  `firstName` VARCHAR(24) NOT NULL,
  `lastName` VARCHAR(24) NOT NULL,
  `userStatus` CHAR(1) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `fd_userID_UNIQUE` (`userID` ASC),
  INDEX `groupID_idx` (`fk_groupID_users` ASC),
  CONSTRAINT `groupID`
    FOREIGN KEY (`fk_groupID_users`)
    REFERENCES `dbMyDreamyCom`.`groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`logs` (
  `logID` INT NOT NULL AUTO_INCREMENT,
  `logType` CHAR(2) NOT NULL,
  `logTime` DATETIME NOT NULL,
  `logAction` VARCHAR(45) NULL,
  `users_userID` INT NOT NULL,
  `groups_groupID` INT NOT NULL,
  PRIMARY KEY (`logID`, `users_userID`, `groups_groupID`),
  INDEX `fk_logs_users1_idx` (`users_userID` ASC),
  INDEX `fk_logs_groups1_idx` (`groups_groupID` ASC),
  CONSTRAINT `fk_logs_users1`
    FOREIGN KEY (`users_userID`)
    REFERENCES `dbMyDreamyCom`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_groups1`
    FOREIGN KEY (`groups_groupID`)
    REFERENCES `dbMyDreamyCom`.`groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`invoices` (
  `invoiceID` INT NOT NULL,
  `fk_users_userID` INT NULL,
  `fk_groups_groupID` INT NULL,
  `invoiceType` VARCHAR(12) NULL,
  `invoiceStatus` VARCHAR(24) NULL,
  `invoiceDate` DATETIME NULL,
  `invoiceAmount` DECIMAL(13) NULL,
  PRIMARY KEY (`invoiceID`, `fk_users_userID`, `fk_groups_groupID`),
  INDEX `fk_invoices_users1_idx` (`fk_users_userID` ASC),
  INDEX `fk_invoices_groups1_idx` (`fk_groups_groupID` ASC),
  CONSTRAINT `fk_invoices_users1`
    FOREIGN KEY (`fk_users_userID`)
    REFERENCES `dbMyDreamyCom`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoices_groups1`
    FOREIGN KEY (`fk_groups_groupID`)
    REFERENCES `dbMyDreamyCom`.`groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`trans` (
  `transID` INT NOT NULL AUTO_INCREMENT,
  `fk_invoices_invoiceID` INT NOT NULL,
  `fk_invoices_users_userID` INT NULL,
  `fk_invoices_groups_groupID` INT NULL,
  `transName` VARCHAR(24) NOT NULL,
  `transTotal` DECIMAL(11) NOT NULL,
  `transTime` DATETIME NOT NULL,
  `transStatus` CHAR(2) NOT NULL,
  `transType` CHAR(1) NOT NULL,
  PRIMARY KEY (`transID`, `fk_invoices_invoiceID`, `fk_invoices_users_userID`, `fk_invoices_groups_groupID`),
  INDEX `fk_trans_invoices1_idx` (`fk_invoices_invoiceID` ASC, `fk_invoices_users_userID` ASC, `fk_invoices_groups_groupID` ASC),
  CONSTRAINT `fk_trans_invoices1`
    FOREIGN KEY (`fk_invoices_invoiceID` , `fk_invoices_users_userID` , `fk_invoices_groups_groupID`)
    REFERENCES `dbMyDreamyCom`.`invoices` (`invoiceID` , `fk_users_userID` , `fk_groups_groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`phones` (
  `phoneID` INT NOT NULL,
  `fk_users_userID` INT NULL,
  `fk_groups_groupID` INT NULL,
  `phoneType` VARCHAR(12) NULL,
  `phoneStatus` CHAR(1) NULL,
  PRIMARY KEY (`phoneID`),
  INDEX `fk_phones_users1_idx` (`fk_users_userID` ASC),
  INDEX `fk_phones_groups1_idx` (`fk_groups_groupID` ASC),
  CONSTRAINT `fk_phones_users1`
    FOREIGN KEY (`fk_users_userID`)
    REFERENCES `dbMyDreamyCom`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_groups1`
    FOREIGN KEY (`fk_groups_groupID`)
    REFERENCES `dbMyDreamyCom`.`groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`addrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`addrs` (
  `addressID` INT NOT NULL,
  `fk_users_userID` INT NULL,
  `fk_groups_groupID` INT NULL,
  `addressStreet` VARCHAR(45) NULL,
  `addressSuite` VARCHAR(24) NULL,
  `addressCity` VARCHAR(45) NULL,
  `addressState` CHAR(2) NULL,
  `addressType` VARCHAR(12) NULL,
  `addressStatus` CHAR(1) NULL,
  `addressNote` VARCHAR(45) NULL,
  PRIMARY KEY (`addressID`),
  INDEX `fk_phones_users1_idx` (`fk_users_userID` ASC),
  INDEX `fk_phones_groups1_idx` (`fk_groups_groupID` ASC),
  CONSTRAINT `fk_phones_users10`
    FOREIGN KEY (`fk_users_userID`)
    REFERENCES `dbMyDreamyCom`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_groups10`
    FOREIGN KEY (`fk_groups_groupID`)
    REFERENCES `dbMyDreamyCom`.`groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`garments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`garments` (
  `garmentID` INT NOT NULL,
  `garmentType` VARCHAR(24) NULL,
  `garmentName` VARCHAR(45) NULL,
  `garmentStyleNo` VARCHAR(24) NULL,
  `garmentUnitPrice` DECIMAL(13) NULL,
  `garmentStatus` VARCHAR(24) NULL,
  `garmentSample` VARCHAR(24) NULL,
  PRIMARY KEY (`garmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMyDreamyCom`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyDreamyCom`.`items` (
  `itemsID` INT NOT NULL,
  `fk_invoices_invoiceID` INT NOT NULL,
  `fk_invoices_fk_users_userID` INT NULL,
  `fk_invoices_fk_groups_groupID` INT NULL,
  `itemStatus` VARCHAR(45) NULL,
  `itemRate` DECIMAL(13) NULL,
  `itemTaxable` CHAR(1) NULL,
  `itemQty` INT NULL,
  `itemAmount` VARCHAR(45) NULL,
  `itemTax` DECIMAL(13) NULL,
  `garments_garmentID` INT NOT NULL,
  PRIMARY KEY (`itemsID`, `fk_invoices_invoiceID`, `fk_invoices_fk_users_userID`, `fk_invoices_fk_groups_groupID`),
  INDEX `fk_items_invoices1_idx` (`fk_invoices_invoiceID` ASC, `fk_invoices_fk_users_userID` ASC, `fk_invoices_fk_groups_groupID` ASC),
  INDEX `fk_items_garments1_idx` (`garments_garmentID` ASC),
  CONSTRAINT `fk_items_invoices1`
    FOREIGN KEY (`fk_invoices_invoiceID` , `fk_invoices_fk_users_userID` , `fk_invoices_fk_groups_groupID`)
    REFERENCES `dbMyDreamyCom`.`invoices` (`invoiceID` , `fk_users_userID` , `fk_groups_groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_garments1`
    FOREIGN KEY (`garments_garmentID`)
    REFERENCES `dbMyDreamyCom`.`garments` (`garmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
